version: '3.9'
services:
  devcontainer:
    build:
      context: .
    volumes:
      - ./:/code
      - ./.devcontainer/git-hooks:/code/.git/hooks
      - /code/node_modules
      - /code/dist
      - /code/tmp
      - /code/.nx_cache
      - /code/.npm
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh
    tty: true
    environment:
      SAMPLE_DATABASE_URL: postgresql://postgres:mysecretpassword@pgvector_db:5432/sampleDb?schema=public
  postgres_db:
    image: postgres:13.6-alpine
    expose:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
volumes:
  pgvector-data:
